version: '3.8'

volumes:
  postgresql:
  postgresql_data:
  pgadmin_data:

services:
  pgdb:
    image: postgres:12.6
    environment:
      - TZ=${TZ}
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    volumes:
      - ./docker-entrypoint.d:/docker-entrypoint-initdb.d:Z
      - postgresql:/var/lib/postgresql:Z
      - postgresql_data:/var/lib/postgresql/data:Z
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:4.25
    depends_on:
      - pgdb
    environment:
      - TZ=${TZ}
      - PGADMIN_DEFAULT_EMAIL=admin
      - PGADMIN_DEFAULT_PASSWORD=password
    volumes:
      - pgadmin_data:/var/lib/pgadmin:Z
    ports:
      - "8082:80"
